logging:
  level:
    org.springframework.security: DEBUG
spring:
  jackson:
    default-property-inclusion: non_absent
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  h2:
    console:
      enabled: true
  web:
    resources:
      static-locations: classpath:/META-INF/resources/webauthn/node_modules,classpath:/static
webauthn:
  relying-party-id: chatty-toys-march-86-126-30-191.loca.lt
  relying-party-name: WebAuthn Application
  relying-party-origins: https://chatty-toys-march-86-126-30-191.loca.lt,android:apk-key-hash:t5OwAx-0r2saAq-IRdO8SuK_hkZWOglhkDSwg7OSpFE
  registrationNewUsers:
    enabled: true
  username-required: false
  endpoints:
    registrationStartPath: /api/registration/start
    registrationAddPath: /api/registration/add
    registrationFinishPath: /api/registration/finish
    assertionStartPath: /api/assertion/start
    assertionFinishPath: /api/assertion/finish
